List<Map<String, String>> getCountryOptions() {
  return [
    {"name": "United Kingdom", "code": "GB"},
    {"name": "Pakistan", "code": "PK"},
    {"name": "Somalia", "code": "SO"},
    {"name": "Aruba", "code": "AW"},
    {"name": "Afghanistan", "code": "AF"},
    {"name": "Angola", "code": "AO"},
    {"name": "Anguilla", "code": "AI"},
    {"name": "\u00c5land Islands", "code": "AX"},
    {"name": "Albania", "code": "AL"},
    {"name": "Andorra", "code": "AD"},
    {"name": "United Arab Emirates", "code": "AE"},
    {"name": "Argentina", "code": "AR"},
    {"name": "Armenia", "code": "AM"},
    {"name": "American Samoa", "code": "AS"},
    {"name": "Antarctica", "code": "AQ"},
    {"name": "French Southern Territories", "code": "TF"},
    {"name": "Antigua and Barbuda", "code": "AG"},
    {"name": "Australia", "code": "AU"},
    {"name": "Austria", "code": "AT"},
    {"name": "Azerbaijan", "code": "AZ"},
    {"name": "Burundi", "code": "BI"},
    {"name": "Belgium", "code": "BE"},
    {"name": "Benin", "code": "BJ"},
    {"name": "Bonaire, Sint Eustatius and Saba", "code": "BQ"},
    {"name": "Burkina Faso", "code": "BF"},
    {"name": "Bangladesh", "code": "BD"},
    {"name": "Bulgaria", "code": "BG"},
    {"name": "Bahrain", "code": "BH"},
    {"name": "Bahamas", "code": "BS"},
    {"name": "Bosnia and Herzegovina", "code": "BA"},
    {"name": "Saint Barth\u00e9lemy", "code": "BL"},
    {"name": "Belarus", "code": "BY"},
    {"name": "Belize", "code": "BZ"},
    {"name": "Bermuda", "code": "BM"},
    {"name": "Bolivia, Plurinational State of", "code": "BO"},
    {"name": "Brazil", "code": "BR"},
    {"name": "Barbados", "code": "BB"},
    {"name": "Brunei Darussalam", "code": "BN"},
    {"name": "Bhutan", "code": "BT"},
    {"name": "Bouvet Island", "code": "BV"},
    {"name": "Botswana", "code": "BW"},
    {"name": "Central African Republic", "code": "CF"},
    {"name": "Canada", "code": "CA"},
    {"name": "Cocos (Keeling) Islands", "code": "CC"},
    {"name": "Switzerland", "code": "CH"},
    {"name": "Chile", "code": "CL"},
    {"name": "China", "code": "CN"},
    {"name": "C\u00f4te d'Ivoire", "code": "CI"},
    {"name": "Cameroon", "code": "CM"},
    {"name": "Congo, The Democratic Republic of the", "code": "CD"},
    {"name": "Congo", "code": "CG"},
    {"name": "Cook Islands", "code": "CK"},
    {"name": "Colombia", "code": "CO"},
    {"name": "Comoros", "code": "KM"},
    {"name": "Cabo Verde", "code": "CV"},
    {"name": "Costa Rica", "code": "CR"},
    {"name": "Cuba", "code": "CU"},
    {"name": "Cura\u00e7ao", "code": "CW"},
    {"name": "Christmas Island", "code": "CX"},
    {"name": "Cayman Islands", "code": "KY"},
    {"name": "Cyprus", "code": "CY"},
    {"name": "Czechia", "code": "CZ"},
    {"name": "Germany", "code": "DE"},
    {"name": "Djibouti", "code": "DJ"},
    {"name": "Dominica", "code": "DM"},
    {"name": "Denmark", "code": "DK"},
    {"name": "Dominican Republic", "code": "DO"},
    {"name": "Algeria", "code": "DZ"},
    {"name": "Ecuador", "code": "EC"},
    {"name": "Egypt", "code": "EG"},
    {"name": "Eritrea", "code": "ER"},
    {"name": "Western Sahara", "code": "EH"},
    {"name": "Spain", "code": "ES"},
    {"name": "Estonia", "code": "EE"},
    {"name": "Ethiopia", "code": "ET"},
    {"name": "Finland", "code": "FI"},
    {"name": "Fiji", "code": "FJ"},
    {"name": "Falkland Islands (Malvinas)", "code": "FK"},
    {"name": "France", "code": "FR"},
    {"name": "Faroe Islands", "code": "FO"},
    {"name": "Micronesia, Federated States of", "code": "FM"},
    {"name": "Gabon", "code": "GA"},
    {"name": "Georgia", "code": "GE"},
    {"name": "Guernsey", "code": "GG"},
    {"name": "Ghana", "code": "GH"},
    {"name": "Gibraltar", "code": "GI"},
    {"name": "Guinea", "code": "GN"},
    {"name": "Guadeloupe", "code": "GP"},
    {"name": "Gambia", "code": "GM"},
    {"name": "Guinea-Bissau", "code": "GW"},
    {"name": "Equatorial Guinea", "code": "GQ"},
    {"name": "Greece", "code": "GR"},
    {"name": "Grenada", "code": "GD"},
    {"name": "Greenland", "code": "GL"},
    {"name": "Guatemala", "code": "GT"},
    {"name": "French Guiana", "code": "GF"},
    {"name": "Guam", "code": "GU"},
    {"name": "Guyana", "code": "GY"},
    {"name": "Hong Kong", "code": "HK"},
    {"name": "Heard Island and McDonald Islands", "code": "HM"},
    {"name": "Honduras", "code": "HN"},
    {"name": "Croatia", "code": "HR"},
    {"name": "Haiti", "code": "HT"},
    {"name": "Hungary", "code": "HU"},
    {"name": "Indonesia", "code": "ID"},
    {"name": "Isle of Man", "code": "IM"},
    {"name": "India", "code": "IN"},
    {"name": "British Indian Ocean Territory", "code": "IO"},
    {"name": "Ireland", "code": "IE"},
    {"name": "Iran, Islamic Republic of", "code": "IR"},
    {"name": "Iraq", "code": "IQ"},
    {"name": "Iceland", "code": "IS"},
    {"name": "Israel", "code": "IL"},
    {"name": "Italy", "code": "IT"},
    {"name": "Jamaica", "code": "JM"},
    {"name": "Jersey", "code": "JE"},
    {"name": "Jordan", "code": "JO"},
    {"name": "Japan", "code": "JP"},
    {"name": "Kazakhstan", "code": "KZ"},
    {"name": "Kenya", "code": "KE"},
    {"name": "Kyrgyzstan", "code": "KG"},
    {"name": "Cambodia", "code": "KH"},
    {"name": "Kiribati", "code": "KI"},
    {"name": "Saint Kitts and Nevis", "code": "KN"},
    {"name": "Korea, Republic of", "code": "KR"},
    {"name": "Kuwait", "code": "KW"},
    {"name": "Lao People's Democratic Republic", "code": "LA"},
    {"name": "Lebanon", "code": "LB"},
    {"name": "Liberia", "code": "LR"},
    {"name": "Libya", "code": "LY"},
    {"name": "Saint Lucia", "code": "LC"},
    {"name": "Liechtenstein", "code": "LI"},
    {"name": "Sri Lanka", "code": "LK"},
    {"name": "Lesotho", "code": "LS"},
    {"name": "Lithuania", "code": "LT"},
    {"name": "Luxembourg", "code": "LU"},
    {"name": "Latvia", "code": "LV"},
    {"name": "Macao", "code": "MO"},
    {"name": "Saint Martin (French part)", "code": "MF"},
    {"name": "Morocco", "code": "MA"},
    {"name": "Monaco", "code": "MC"},
    {"name": "Moldova, Republic of", "code": "MD"},
    {"name": "Madagascar", "code": "MG"},
    {"name": "Maldives", "code": "MV"},
    {"name": "Mexico", "code": "MX"},
    {"name": "Marshall Islands", "code": "MH"},
    {"name": "North Macedonia", "code": "MK"},
    {"name": "Mali", "code": "ML"},
    {"name": "Malta", "code": "MT"},
    {"name": "Myanmar", "code": "MM"},
    {"name": "Montenegro", "code": "ME"},
    {"name": "Mongolia", "code": "MN"},
    {"name": "Northern Mariana Islands", "code": "MP"},
    {"name": "Mozambique", "code": "MZ"},
    {"name": "Mauritania", "code": "MR"},
    {"name": "Montserrat", "code": "MS"},
    {"name": "Martinique", "code": "MQ"},
    {"name": "Mauritius", "code": "MU"},
    {"name": "Malawi", "code": "MW"},
    {"name": "Malaysia", "code": "MY"},
    {"name": "Mayotte", "code": "YT"},
    {"name": "Namibia", "code": "NA"},
    {"name": "New Caledonia", "code": "NC"},
    {"name": "Niger", "code": "NE"},
    {"name": "Norfolk Island", "code": "NF"},
    {"name": "Nigeria", "code": "NG"},
    {"name": "Nicaragua", "code": "NI"},
    {"name": "Niue", "code": "NU"},
    {"name": "Netherlands", "code": "NL"},
    {"name": "Norway", "code": "NO"},
    {"name": "Nepal", "code": "NP"},
    {"name": "Nauru", "code": "NR"},
    {"name": "New Zealand", "code": "NZ"},
    {"name": "Oman", "code": "OM"},
    {"name": "Panama", "code": "PA"},
    {"name": "Pitcairn", "code": "PN"},
    {"name": "Peru", "code": "PE"},
    {"name": "Philippines", "code": "PH"},
    {"name": "Palau", "code": "PW"},
    {"name": "Papua New Guinea", "code": "PG"},
    {"name": "Poland", "code": "PL"},
    {"name": "Puerto Rico", "code": "PR"},
    {"name": "Korea, Democratic People's Republic of", "code": "KP"},
    {"name": "Portugal", "code": "PT"},
    {"name": "Paraguay", "code": "PY"},
    {"name": "Palestine, State of", "code": "PS"},
    {"name": "French Polynesia", "code": "PF"},
    {"name": "Qatar", "code": "QA"},
    {"name": "R\u00e9union", "code": "RE"},
    {"name": "Romania", "code": "RO"},
    {"name": "Russian Federation", "code": "RU"},
    {"name": "Rwanda", "code": "RW"},
    {"name": "Saudi Arabia", "code": "SA"},
    {"name": "Sudan", "code": "SD"},
    {"name": "Senegal", "code": "SN"},
    {"name": "Singapore", "code": "SG"},
    {"name": "South Georgia and the South Sandwich Islands", "code": "GS"},
    {"name": "Saint Helena, Ascension and Tristan da Cunha", "code": "SH"},
    {"name": "Svalbard and Jan Mayen", "code": "SJ"},
    {"name": "Solomon Islands", "code": "SB"},
    {"name": "Sierra Leone", "code": "SL"},
    {"name": "El Salvador", "code": "SV"},
    {"name": "San Marino", "code": "SM"},
    {"name": "Saint Pierre and Miquelon", "code": "PM"},
    {"name": "Serbia", "code": "RS"},
    {"name": "South Sudan", "code": "SS"},
    {"name": "Sao Tome and Principe", "code": "ST"},
    {"name": "Suriname", "code": "SR"},
    {"name": "Slovakia", "code": "SK"},
    {"name": "Slovenia", "code": "SI"},
    {"name": "Sweden", "code": "SE"},
    {"name": "Eswatini", "code": "SZ"},
    {"name": "Sint Maarten (Dutch part)", "code": "SX"},
    {"name": "Seychelles", "code": "SC"},
    {"name": "Syrian Arab Republic", "code": "SY"},
    {"name": "Turks and Caicos Islands", "code": "TC"},
    {"name": "Chad", "code": "TD"},
    {"name": "Togo", "code": "TG"},
    {"name": "Thailand", "code": "TH"},
    {"name": "Tajikistan", "code": "TJ"},
    {"name": "Tokelau", "code": "TK"},
    {"name": "Turkmenistan", "code": "TM"},
    {"name": "Timor-Leste", "code": "TL"},
    {"name": "Tonga", "code": "TO"},
    {"name": "Trinidad and Tobago", "code": "TT"},
    {"name": "Tunisia", "code": "TN"},
    {"name": "Turkey", "code": "TR"},
    {"name": "Tuvalu", "code": "TV"},
    {"name": "Taiwan, Province of China", "code": "TW"},
    {"name": "Tanzania, United Republic of", "code": "TZ"},
    {"name": "Uganda", "code": "UG"},
    {"name": "Ukraine", "code": "UA"},
    {"name": "United States Minor Outlying Islands", "code": "UM"},
    {"name": "Uruguay", "code": "UY"},
    {"name": "United States", "code": "US"},
    {"name": "Uzbekistan", "code": "UZ"},
    {"name": "Holy See (Vatican City State)", "code": "VA"},
    {"name": "Saint Vincent and the Grenadines", "code": "VC"},
    {"name": "Venezuela, Bolivarian Republic of", "code": "VE"},
    {"name": "Virgin Islands, British", "code": "VG"},
    {"name": "Virgin Islands, U.S.", "code": "VI"},
    {"name": "Viet Nam", "code": "VN"},
    {"name": "Vanuatu", "code": "VU"},
    {"name": "Wallis and Futuna", "code": "WF"},
    {"name": "Samoa", "code": "WS"},
    {"name": "Yemen", "code": "YE"},
    {"name": "South Africa", "code": "ZA"},
    {"name": "Zambia", "code": "ZM"},
    {"name": "Zimbabwe", "code": "ZW"}
  ];
}

List<Map<String, dynamic>> getLanguages() {
  return [
    {"name": "Arabic", "value": 1},
    {"name": "Bengali", "value": 2},
    {"name": "Chinese", "value": 3},
    {"name": "Dutch", "value": 4},
    {"name": "English", "value": 5},
    {"name": "French", "value": 6},
    {"name": "German", "value": 7},
    {"name": "Greek", "value": 8},
    {"name": "Hausa", "value": 9},
    {"name": "Hebrew", "value": 10},
    {"name": "Hindi", "value": 11},
    {"name": "Indonesian", "value": 12},
    {"name": "Italian", "value": 13},
    {"name": "Japanese", "value": 14},
    {"name": "Korean", "value": 15},
    {"name": "Malay", "value": 16},
    {"name": "Persian", "value": 17},
    {"name": "Polish", "value": 18},
    {"name": "Portuguese", "value": 19},
    {"name": "Romanian", "value": 20},
    {"name": "Russian", "value": 21},
    {"name": "Spanish", "value": 22},
    {"name": "Swahili", "value": 23},
    {"name": "Tamil", "value": 24},
    {"name": "Telugu", "value": 25},
    {"name": "Thai", "value": 26},
    {"name": "Turkish", "value": 27},
    {"name": "Ukrainian", "value": 28},
    {"name": "Urdu", "value": 29},
    {"name": "Vietnamese", "value": 30}
  ];
}

List<Map<String, dynamic>> getEthnicities() {
  return [
    {"name": "Arab", "value": 1},
    {"name": "Berber", "value": 2},
    {"name": "Central African", "value": 3},
    {"name": "East African", "value": 4},
    {"name": "North African", "value": 5},
    {"name": "South African", "value": 6},
    {"name": "West African", "value": 7},
    {"name": "Nigerian", "value": 8},
    {"name": "Somali", "value": 9},
    {"name": "Sudanese", "value": 10},
    {"name": "European", "value": 11},
    {"name": "South Asian", "value": 12},
    {"name": "Indian", "value": 13},
    {"name": "Pakistani", "value": 14},
    {"name": "Bangladeshi", "value": 15},
    {"name": "Afghan", "value": 16},
    {"name": "Turkish", "value": 17},
    {"name": "Persian", "value": 18},
    {"name": "Malay", "value": 19},
    {"name": "Indonesian", "value": 20},
    {"name": "Chinese", "value": 21},
    {"name": "Mixed/Other", "value": 22}
  ];
}

List<Map<String, dynamic>> getNationalities() {
  return [
    {"name": "Moroccon", "value": 138},
    {"name": "Pakistani", "value": 173},
    {"name": "British", "value": 80},
    {"name": "Indian", "value": 105},
    {"name": "Aruban", "value": 1},
    {"name": "Afghan", "value": 2},
    {"name": "Angolan", "value": 3},
    {"name": "Anguillan", "value": 4},
    {"name": "\u00c5land Islandsn", "value": 5},
    {"name": "Albanian", "value": 6},
    {"name": "Andorran", "value": 7},
    {"name": "United Arab Emiratesn", "value": 8},
    {"name": "Argentinan", "value": 9},
    {"name": "Armenian", "value": 10},
    {"name": "American Samoan", "value": 11},
    {"name": "Antarctican", "value": 12},
    {"name": "French Southern Territoriesn", "value": 13},
    {"name": "Antigua and Barbudan", "value": 14},
    {"name": "Australian", "value": 15},
    {"name": "Austrian", "value": 16},
    {"name": "Azerbaijann", "value": 17},
    {"name": "Burundin", "value": 18},
    {"name": "Belgiumn", "value": 19},
    {"name": "Beninn", "value": 20},
    {"name": "Bonaire, Sint Eustatius and Saban", "value": 21},
    {"name": "Burkina Fason", "value": 22},
    {"name": "Bangladeshi", "value": 23},
    {"name": "Bulgarian", "value": 24},
    {"name": "Bahrainn", "value": 25},
    {"name": "Bahamasn", "value": 26},
    {"name": "Bosnia and Herzegovinan", "value": 27},
    {"name": "Saint Barth\u00e9lemyn", "value": 28},
    {"name": "Belarusn", "value": 29},
    {"name": "Belizen", "value": 30},
    {"name": "Bermudan", "value": 31},
    {"name": "Bolivia, Plurinational State ofn", "value": 32},
    {"name": "Braziln", "value": 33},
    {"name": "Barbadosn", "value": 34},
    {"name": "Brunei Darussalamn", "value": 35},
    {"name": "Bhutann", "value": 36},
    {"name": "Bouvet Islandn", "value": 37},
    {"name": "Botswanan", "value": 38},
    {"name": "Central African Republicn", "value": 39},
    {"name": "Canadan", "value": 40},
    {"name": "Cocos (Keeling) Islandsn", "value": 41},
    {"name": "Switzerlandn", "value": 42},
    {"name": "Chilen", "value": 43},
    {"name": "Chinese", "value": 44},
    {"name": "C\u00f4te d'Ivoiren", "value": 45},
    {"name": "Cameroonn", "value": 46},
    {"name": "Congo, The Democratic Republic of then", "value": 47},
    {"name": "Congon", "value": 48},
    {"name": "Cook Islandsn", "value": 49},
    {"name": "Colombian", "value": 50},
    {"name": "Comorosn", "value": 51},
    {"name": "Cabo Verden", "value": 52},
    {"name": "Costa Rican", "value": 53},
    {"name": "Cuban", "value": 54},
    {"name": "Cura\u00e7aon", "value": 55},
    {"name": "Christmas Islandn", "value": 56},
    {"name": "Cayman Islandsn", "value": 57},
    {"name": "Cyprusn", "value": 58},
    {"name": "Czechian", "value": 59},
    {"name": "German", "value": 60},
    {"name": "Djiboutin", "value": 61},
    {"name": "Dominican", "value": 62},
    {"name": "Denmarkn", "value": 63},
    {"name": "Dominican Republicn", "value": 64},
    {"name": "Algerian", "value": 65},
    {"name": "Ecuadorn", "value": 66},
    {"name": "Egyptian", "value": 67},
    {"name": "Eritrean", "value": 68},
    {"name": "Western Saharan", "value": 69},
    {"name": "Spainn", "value": 70},
    {"name": "Estonian", "value": 71},
    {"name": "Ethiopian", "value": 72},
    {"name": "Finlandn", "value": 73},
    {"name": "Fijin", "value": 74},
    {"name": "Falkland Islands (Malvinas)n", "value": 75},
    {"name": "French", "value": 76},
    {"name": "Faroe Islandsn", "value": 77},
    {"name": "Micronesia, Federated States ofn", "value": 78},
    {"name": "Gabonn", "value": 79},
    {"name": "Georgian", "value": 81},
    {"name": "Guernseyn", "value": 82},
    {"name": "Ghanan", "value": 83},
    {"name": "Gibraltarn", "value": 84},
    {"name": "Guinean", "value": 85},
    {"name": "Guadeloupen", "value": 86},
    {"name": "Gambian", "value": 87},
    {"name": "Guinea-Bissaun", "value": 88},
    {"name": "Equatorial Guinean", "value": 89},
    {"name": "Greecen", "value": 90},
    {"name": "Grenadan", "value": 91},
    {"name": "Greenlandn", "value": 92},
    {"name": "Guatemalan", "value": 93},
    {"name": "French Guianan", "value": 94},
    {"name": "Guamn", "value": 95},
    {"name": "Guyanan", "value": 96},
    {"name": "Hong Kongn", "value": 97},
    {"name": "Heard Island and McDonald Islandsn", "value": 98},
    {"name": "Hondurasn", "value": 99},
    {"name": "Croatian", "value": 100},
    {"name": "Haitin", "value": 101},
    {"name": "Hungaryn", "value": 102},
    {"name": "Indonesian", "value": 103},
    {"name": "Isle of Mann", "value": 104},
    {"name": "British Indian Ocean Territoryn", "value": 106},
    {"name": "Irelandn", "value": 107},
    {"name": "Iranian", "value": 108},
    {"name": "Iraqi", "value": 109},
    {"name": "Icelandn", "value": 110},
    {"name": "Israeln", "value": 111},
    {"name": "Italyn", "value": 112},
    {"name": "Jamaican", "value": 113},
    {"name": "Jerseyn", "value": 114},
    {"name": "Jordann", "value": 115},
    {"name": "Japanese", "value": 116},
    {"name": "Kazakhstann", "value": 117},
    {"name": "Kenyan", "value": 118},
    {"name": "Kyrgyzstann", "value": 119},
    {"name": "Cambodian", "value": 120},
    {"name": "Kiribatin", "value": 121},
    {"name": "Saint Kitts and Nevisn", "value": 122},
    {"name": "Korea, Republic ofn", "value": 123},
    {"name": "Kuwaitn", "value": 124},
    {"name": "Lao People's Democratic Republicn", "value": 125},
    {"name": "Lebanonn", "value": 126},
    {"name": "Liberian", "value": 127},
    {"name": "Libyan", "value": 128},
    {"name": "Saint Lucian", "value": 129},
    {"name": "Liechtensteinn", "value": 130},
    {"name": "Sri Lankan", "value": 131},
    {"name": "Lesothon", "value": 132},
    {"name": "Lithuanian", "value": 133},
    {"name": "Luxembourgn", "value": 134},
    {"name": "Latvian", "value": 135},
    {"name": "Macaon", "value": 136},
    {"name": "Saint Martin (French part)n", "value": 137},
    {"name": "Monacon", "value": 139},
    {"name": "Moldova, Republic ofn", "value": 140},
    {"name": "Madagascarn", "value": 141},
    {"name": "Maldivesn", "value": 142},
    {"name": "Mexicon", "value": 143},
    {"name": "Marshall Islandsn", "value": 144},
    {"name": "North Macedonian", "value": 145},
    {"name": "Malin", "value": 146},
    {"name": "Maltan", "value": 147},
    {"name": "Myanmarn", "value": 148},
    {"name": "Montenegron", "value": 149},
    {"name": "Mongolian", "value": 150},
    {"name": "Northern Mariana Islandsn", "value": 151},
    {"name": "Mozambiquen", "value": 152},
    {"name": "Mauritanian", "value": 153},
    {"name": "Montserratn", "value": 154},
    {"name": "Martiniquen", "value": 155},
    {"name": "Mauritiusn", "value": 156},
    {"name": "Malawin", "value": 157},
    {"name": "Malaysian", "value": 158},
    {"name": "Mayotten", "value": 159},
    {"name": "Namibian", "value": 160},
    {"name": "New Caledonian", "value": 161},
    {"name": "Nigern", "value": 162},
    {"name": "Norfolk Islandn", "value": 163},
    {"name": "Nigerian", "value": 164},
    {"name": "Nicaraguan", "value": 165},
    {"name": "Niuen", "value": 166},
    {"name": "Netherlandsn", "value": 167},
    {"name": "Norwayn", "value": 168},
    {"name": "Nepaln", "value": 169},
    {"name": "Naurun", "value": 170},
    {"name": "New Zealandn", "value": 171},
    {"name": "Omann", "value": 172},
    {"name": "Panaman", "value": 174},
    {"name": "Pitcairnn", "value": 175},
    {"name": "Perun", "value": 176},
    {"name": "Philippinesn", "value": 177},
    {"name": "Palaun", "value": 178},
    {"name": "Papua New Guinean", "value": 179},
    {"name": "Polandn", "value": 180},
    {"name": "Puerto Ricon", "value": 181},
    {"name": "Korea, Democratic People's Republic ofn", "value": 182},
    {"name": "Portugaln", "value": 183},
    {"name": "Paraguayn", "value": 184},
    {"name": "Palestine, State ofn", "value": 185},
    {"name": "French Polynesian", "value": 186},
    {"name": "Qatarn", "value": 187},
    {"name": "R\u00e9unionn", "value": 188},
    {"name": "Romanian", "value": 189},
    {"name": "Russian Federationn", "value": 190},
    {"name": "Rwandan", "value": 191},
    {"name": "Saudi Arabian", "value": 192},
    {"name": "Sudann", "value": 193},
    {"name": "Senegaln", "value": 194},
    {"name": "Singaporen", "value": 195},
    {"name": "South Georgia and the South Sandwich Islandsn", "value": 196},
    {"name": "Saint Helena, Ascension and Tristan da Cunhan", "value": 197},
    {"name": "Svalbard and Jan Mayenn", "value": 198},
    {"name": "Solomon Islandsn", "value": 199},
    {"name": "Sierra Leonen", "value": 200},
    {"name": "El Salvadorn", "value": 201},
    {"name": "San Marinon", "value": 202},
    {"name": "Somalian", "value": 203},
    {"name": "Saint Pierre and Miquelonn", "value": 204},
    {"name": "Serbian", "value": 205},
    {"name": "South Sudann", "value": 206},
    {"name": "Sao Tome and Principen", "value": 207},
    {"name": "Surinamen", "value": 208},
    {"name": "Slovakian", "value": 209},
    {"name": "Slovenian", "value": 210},
    {"name": "Swedenn", "value": 211},
    {"name": "Eswatinin", "value": 212},
    {"name": "Sint Maarten (Dutch part)n", "value": 213},
    {"name": "Seychellesn", "value": 214},
    {"name": "Syrian Arab Republicn", "value": 215},
    {"name": "Turks and Caicos Islandsn", "value": 216},
    {"name": "Chadn", "value": 217},
    {"name": "Togon", "value": 218},
    {"name": "Thailandn", "value": 219},
    {"name": "Tajikistann", "value": 220},
    {"name": "Tokelaun", "value": 221},
    {"name": "Turkmenistann", "value": 222},
    {"name": "Timor-Lesten", "value": 223},
    {"name": "Tongan", "value": 224},
    {"name": "Trinidad and Tobagon", "value": 225},
    {"name": "Tunisian", "value": 226},
    {"name": "Turkish", "value": 227},
    {"name": "Tuvalun", "value": 228},
    {"name": "Taiwan, Province of Chinan", "value": 229},
    {"name": "Tanzania, United Republic ofn", "value": 230},
    {"name": "Ugandan", "value": 231},
    {"name": "Ukrainen", "value": 232},
    {"name": "United States Minor Outlying Islandsn", "value": 233},
    {"name": "Uruguayn", "value": 234},
    {"name": "American", "value": 235},
    {"name": "Uzbekistann", "value": 236},
    {"name": "Holy See (Vatican City State)n", "value": 237},
    {"name": "Saint Vincent and the Grenadinesn", "value": 238},
    {"name": "Venezuela, Bolivarian Republic ofn", "value": 239},
    {"name": "Virgin Islands, Britishn", "value": 240},
    {"name": "Virgin Islands, U.S.n", "value": 241},
    {"name": "Viet Namn", "value": 242},
    {"name": "Vanuatun", "value": 243},
    {"name": "Wallis and Futunan", "value": 244},
    {"name": "Samoan", "value": 245},
    {"name": "Yemenn", "value": 246},
    {"name": "South African", "value": 247},
    {"name": "Zambian", "value": 248},
    {"name": "Zimbabwen", "value": 249}
  ];
}

List<Map<String, dynamic>> getHeightOptions() {
  return [
    {"name": "122 cm (4'0\")", "value": 1},
    {"name": "124 cm (4'1\")", "value": 2},
    {"name": "127 cm (4'2\")", "value": 3},
    {"name": "130 cm (4'3\")", "value": 4},
    {"name": "132 cm (4'4\")", "value": 5},
    {"name": "135 cm (4'5\")", "value": 6},
    {"name": "137 cm (4'6\")", "value": 7},
    {"name": "140 cm (4'7\")", "value": 8},
    {"name": "142 cm (4'8\")", "value": 9},
    {"name": "145 cm (4'9\")", "value": 10},
    {"name": "147 cm (4'10\")", "value": 11},
    {"name": "150 cm (4'11\")", "value": 12},
    {"name": "152 cm (5'0\")", "value": 13},
    {"name": "155 cm (5'1\")", "value": 14},
    {"name": "157 cm (5'2\")", "value": 15},
    {"name": "160 cm (5'3\")", "value": 16},
    {"name": "163 cm (5'4\")", "value": 17},
    {"name": "165 cm (5'5\")", "value": 18},
    {"name": "168 cm (5'6\")", "value": 19},
    {"name": "170 cm (5'7\")", "value": 20},
    {"name": "173 cm (5'8\")", "value": 21},
    {"name": "175 cm (5'9\")", "value": 22},
    {"name": "178 cm (5'10\")", "value": 23},
    {"name": "180 cm (5'11\")", "value": 24},
    {"name": "183 cm (6'0\")", "value": 25},
    {"name": "185 cm (6'1\")", "value": 26},
    {"name": "188 cm (6'2\")", "value": 27},
    {"name": "190 cm (6'3\")", "value": 28},
    {"name": "193 cm (6'4\")", "value": 29},
    {"name": "196 cm (6'5\")", "value": 30},
    {"name": "198 cm (6'6\")", "value": 31},
    {"name": "201 cm (6'7\")", "value": 32},
    {"name": "203 cm (6'8\")", "value": 33},
    {"name": "206 cm (6'9\")", "value": 34},
    {"name": "208 cm (6'10\")", "value": 35},
    {"name": "211 cm (6'11\")", "value": 36},
    {"name": "213 cm (7'0\")", "value": 37},
    {"name": "216 cm (7'1\")", "value": 38},
    {"name": "218 cm (7'2\")", "value": 39},
    {"name": "221 cm (7'3\")", "value": 40},
    {"name": "224 cm (7'4\")", "value": 41},
    {"name": "226 cm (7'5\")", "value": 42},
    {"name": "229 cm (7'6\")", "value": 43},
    {"name": "231 cm (7'7\")", "value": 44},
    {"name": "234 cm (7'8\")", "value": 45},
    {"name": "236 cm (7'9\")", "value": 46},
    {"name": "239 cm (7'10\")", "value": 47},
    {"name": "241 cm (7'11\")", "value": 48},
  ];
}
List<Map<String, dynamic>> getProfessionOptions() {
  return [
    {"name": "Accountant", "value": 1},
    {"name": "Actor", "value": 2},
    {"name": "Administration Professional", "value": 3},
    {"name": "Advertising Professional", "value": 4},
    {"name": "Architect", "value": 5},
    {"name": "Artisan", "value": 6},
    {"name": "Audiologist", "value": 7},
    {"name": "Banker", "value": 8},
    {"name": "Beautician", "value": 9},
    {"name": "Biologist / Botanist", "value": 10},
    {"name": "Business Person", "value": 11},
    {"name": "Chartered Accountant", "value": 12},
    {"name": "Civil Engineer", "value": 13},
    {"name": "Clerical Official", "value": 14},
    {"name": "Company Secretary", "value": 15},
    {"name": "Computer Professional", "value": 16},
    {"name": "Consultant", "value": 17},
    {"name": "Contractor", "value": 18},
    {"name": "Cost Accountant", "value": 19},
    {"name": "Creative Person", "value": 20},
    {"name": "Customer Support Professional", "value": 21},
    {"name": "Defence Employee", "value": 22},
    {"name": "Dentist", "value": 23},
    {"name": "Designer", "value": 24},
    {"name": "Doctor", "value": 25},
    {"name": "Economist", "value": 26},
    {"name": "Engineer", "value": 27},
    {"name": "Engineer (Mechanical)", "value": 28},
    {"name": "Engineer (Project)", "value": 29},
    {"name": "Entertainment Professional", "value": 30},
    {"name": "Event Manager", "value": 31},
    {"name": "Executive", "value": 32},
    {"name": "Factory worker", "value": 33},
    {"name": "Farmer", "value": 34},
    {"name": "Fashion Designer", "value": 35},
    {"name": "Finance Professional", "value": 36},
    {"name": "Flight Attendant", "value": 37},
    {"name": "Government Employee", "value": 38},
    {"name": "Health Care Professional", "value": 39},
    {"name": "Home Maker", "value": 40},
    {"name": "Human Resources Professional", "value": 41},
    {"name": "Interior Designer", "value": 42},
    {"name": "Investment Professional", "value": 43},
    {"name": "IT / Telecom Professional", "value": 44},
    {"name": "Journalist", "value": 45},
    {"name": "Lawyer", "value": 46},
    {"name": "Lecturer", "value": 47},
    {"name": "Legal Professional", "value": 48},
    {"name": "Manager", "value": 49},
    {"name": "Marketing Professional", "value": 50},
    {"name": "Media Professional", "value": 51},
    {"name": "Medical Professional", "value": 52},
    {"name": "Medical Transcriptionist", "value": 53},
    {"name": "Merchant", "value": 54},
    {"name": "Naval Officer", "value": 55},
    {"name": "Non-mainstream professional", "value": 56},
    {"name": "Not working", "value": 57},
    {"name": "Nurse", "value": 58},
    {"name": "Occupational Therapist", "value": 59},
    {"name": "Optician", "value": 60},
    {"name": "Pharmacist", "value": 61},
    {"name": "Physician Assistant", "value": 62},
    {"name": "Physicist", "value": 63},
    {"name": "Physiotherapist", "value": 64},
    {"name": "Pilot", "value": 65},
    {"name": "Politician", "value": 66},
    {"name": "Production professional", "value": 67},
    {"name": "Professor", "value": 68},
    {"name": "Psychologist", "value": 69},
    {"name": "Public Relations Professional", "value": 70},
    {"name": "Real Estate Professional", "value": 71},
    {"name": "Research Scholar", "value": 72},
    {"name": "Retail Professional", "value": 73},
    {"name": "Retired Person", "value": 74},
    {"name": "Sales Professional", "value": 75},
    {"name": "Scientist", "value": 76},
    {"name": "Self-employed Person", "value": 77},
    {"name": "Social Worker", "value": 78},
    {"name": "Software Consultant", "value": 79},
    {"name": "Sportsman", "value": 80},
    {"name": "Student", "value": 81},
    {"name": "Teacher", "value": 82},
    {"name": "Technician", "value": 83},
    {"name": "Training Professional", "value": 84},
    {"name": "Transportation Professional", "value": 85},
    {"name": "Veterinary Doctor", "value": 86},
    {"name": "Volunteer", "value": 87},
    {"name": "Writer", "value": 88},
    {"name": "Zoologist", "value": 89},
    {"name": "Other", "value": 90}
  ];
}